version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/did_you_know
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - did_you_know-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: did_you_know
      POSTGRES_PASSWORD: postgres

  dbqa:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - did_you_know-qa-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: did_you_know_qa
      POSTGRES_PASSWORD: postgres
  
  pgweb:
    image: sosedoff/pgweb:latest
    restart: unless-stopped
    ports:
      - "8085:8081"
    environment:
      # We use the service name 'db' from above as the host
      - DATABASE_URL=postgres://postgres:postgres@db:5432/did_you_know?sslmode=disable
    depends_on:
      - db

    # Add "forwardPorts": [5432] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  did_you_know-data:
  did_you_know-qa-data:
